sudo: required

dist: trusty

language: python

python: '2.7'

cache:
  - pip

before_install:
  - sudo apt-get install -qq -y cython liblapack-dev libhdf5-dev

install:
  - pip install -r requirements.txt

script:
  - pip install hacking
  - flake8 .

branches:
  only:
    - master
